name: Production environment CI pipeline
on: 
    workflow_dispatch:
      inputs:
        action:
            description: "Terraform action"
            required: true
            default: "apply"
            type: choice
            options:
            - apply
            - bootstrap
            - destroy-all
        env:
            description: "environment"
            required: true
            default: "dev"
            type: choice
            options:
                - dev
                - prod
concurrency:
  group: terraform-${{ inputs.env }}
  cancel-in-progress: false
jobs:
    call-terraform:
        uses: ./.github/workflows/workflow-call.yaml
        with: 
            env : ${{ inputs.env }}
            action: ${{ inputs.action }}
            aws_region: ${{ vars.AWS_REGION }}
        secrets: inherit
    
           
