name: validate and deploy workflow
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to target"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
      action:
        description: "Terraform action"
        required: true
        default: "destroy"
        type: choice
        options:
          - destroy

  # pull_request:
  #   branches:
  #     - dev
  #     - main
  #     - demo
  #   paths:
  #     - 'infra/modules/**'
  #     - 'terragrunt/us-east-1/**'
  #     - '.github/workflows/validate-Infra-manifest.yaml'

  # push:
  #   branches:
  #     - dev
  #     - main
  #     - demo
  #   paths:
  #     - 'infra/modules/**'
  #     - 'terragrunt/us-east-1/**'
  #     - '.github/workflows/validate-Infra-manifest.yaml'

concurrency:
  group: gitops-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  detect-changes:
    name: Detect Changed Services
    runs-on: ubuntu-latest
    outputs:
      workflow_changed: ${{ steps.extract.outputs.workflow_changed }}
      terraform_modules_changed: ${{ steps.extract.outputs.terraform_modules_changed }}
      terraform_modules: ${{ steps.extract.outputs.terraform_modules }}
      terragrunt_modules_changed: ${{ steps.extract.outputs.terragrunt_modules_changed }}
      terragrunt_modules: ${{ steps.extract.outputs.terragrunt_modules }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Paths Filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          list-files: shell
          filters: |
            terraform-modules:
              - 'infra/modules/**'
            terragrunt-modules:
              - 'terragrunt/us-east-1/**'
            workflow:
              - '.github/workflows/validate-Infra-manifest.yaml'

      - name: Extract service list from changed files
        id: extract
        run: |
          set -euo pipefail

          # TERRAFORM MODULES
          TF_MODULES_FILES="${{ steps.filter.outputs.terraform-modules_files }}"
          if [ -n "$TF_MODULES_FILES" ]; then
            TF_MODULES=$(echo "$TF_MODULES_FILES" | tr ' ' '\n' | cut -d'/' -f3 | sort -u | jq -R -s -c 'split("\n") | map(select(length>0))')
            echo "terraform_modules_changed=true" >> $GITHUB_OUTPUT
            echo "terraform_modules=$TF_MODULES" >> $GITHUB_OUTPUT
          else
            echo "terraform_modules_changed=false" >> $GITHUB_OUTPUT
            echo "terraform_modules=[]" >> $GITHUB_OUTPUT
          fi
          
          # TERRAGRUNT MODULES
          TG_FILES="${{ steps.filter.outputs.terragrunt-modules_files }}"
          if [ -n "$TG_FILES" ]; then
            TG=$(echo "$TG_FILES" | tr ' ' '\n' | cut -d'/' -f4 | sort -u | jq -R -s -c 'split("\n") | map(select(length>0))')
            echo "terragrunt_modules_changed=true" >> $GITHUB_OUTPUT
            echo "terragrunt_modules=$TG" >> $GITHUB_OUTPUT
          else
            echo "terragrunt_modules_changed=false" >> $GITHUB_OUTPUT
            echo "terragrunt_modules=[]" >> $GITHUB_OUTPUT
          fi

          if [ "${{ steps.filter.outputs.workflow }}" = "true" ]; then
            echo "workflow_changed=true" >> $GITHUB_OUTPUT
          else
            echo "workflow_changed=false" >> $GITHUB_OUTPUT
          fi

  terraform-scan:
    name: "Terraform Security Scan"
    runs-on: ubuntu-latest
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.terraform_modules_changed == 'true' ||  
      needs.detect-changes.outputs.workflow_changed == 'true' ||
      needs.detect-changes.outputs.terragrunt_modules_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform manifest logic
        working-directory: infra/modules
        run: |
          terraform init -backend=false
          terraform validate

      - name: Run Checkov on Terraform
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/modules
          framework: terraform
          soft_fail: false # true for prod
          skip_check: CKV_AWS_39,CKV_AWS_58
          output_format: cli

  terragrunt-scan:
    name: "Terragrunt logic Scan"
    runs-on: ubuntu-latest
    needs: detect-changes
  
    if: |
      needs.detect-changes.outputs.terragrunt_modules_changed == 'true' ||  
      needs.detect-changes.outputs.workflow_changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terragrunt and OpenTofu
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: '0.82.2'
          tofu_version: '1.10.1'

      - name: Check Terragrunt manifest logic
        working-directory: >-
          terragrunt/us-east-1/${{
            github.event_name == 'workflow_dispatch'
              && github.event.inputs.env
              || github.ref_name == 'main'
              && 'prod'
              || 'dev'
          }}
        run: |
          terragrunt run-all validate
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          AWS_REGION: us-east-1

  secret-scan:
    name: Secret Scan (Gitleaks)
    runs-on: ubuntu-latest
    needs: detect-changes
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source ./ --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  call-terraform-for-dev:
    needs: [detect-changes, terraform-scan, terragrunt-scan,secret-scan]
    if: |
      (
        (
          github.ref == 'refs/heads/dev' ||
          github.ref == 'refs/heads/demo'
        ) &&
        (
          needs.detect-changes.outputs.terragrunt_modules_changed == 'true' ||
          needs.detect-changes.outputs.terraform_modules_changed == 'true' ||
          needs.detect-changes.outputs.workflow_changed == 'true'
        )
      ) ||
      (
        github.event_name == 'workflow_dispatch' &&
        github.event.inputs.env == 'dev'
      )
    uses: ./.github/workflows/workflow-call.yaml
    with: 
      env: dev
      action: ${{ github.event_name == 'pull_request' && 'plan' || (github.event_name == 'push' && 'apply' || github.event.inputs.action) }}
      aws_region: 'us-east-1'
    secrets: inherit
        
  call-terraform-for-prod:
    needs: [detect-changes, terraform-scan, terragrunt-scan, secret-scan]
    if: |
      (
        github.ref == 'refs/heads/main' &&
        (
          needs.detect-changes.outputs.terragrunt_modules_changed == 'true' ||
          needs.detect-changes.outputs.terraform_modules_changed == 'true' ||
          needs.detect-changes.outputs.workflow_changed == 'true'
        )
      ) ||
      (
        github.event_name == 'workflow_dispatch' &&
        github.event.inputs.env == 'prod'
      )
    uses: ./.github/workflows/workflow-call.yaml
    with:
      env: prod
      action: ${{ github.event_name == 'pull_request' && 'plan' || (github.event_name == 'push' && 'apply' || github.event.inputs.action) }}
      aws_region: 'us-east-1'
    secrets: inherit
      
