name: validate and deploy workflow
on:
  workflow_dispatch:
      inputs:
        env:
            description: "env"
            required: true
            default: "dev"
            type: choice
            options:
            - dev
            - prod
        action:
            description: "Terraform action"
            required: true
            default: "apply"
            type: choice
            options:
              - apply
              - destroy
        

  # pull_request:
  #   branches:
  #     - main
  # push:
  #   branches:
  #       - main
  #       - dev
  #   paths:
  #       - infra/**
  #       - terragrunt/**
  #       - .github/workflows/validate-Infra-manifest.yaml
  #   tags:
  #     - "[0-9]*.[0-9]*.[0-9]*"
concurrency:
  group: gitops-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
  detect-changes:
    name: Detect Changed Services
    runs-on: ubuntu-latest
    outputs:

      workflow_changed: ${{ steps.extract.outputs.workflow_changed }}

      terraform_modules_changed: ${{ steps.extract.outputs.terraform_modules_changed }}
      terraform_modules: ${{ steps.extract.outputs.terraform_modules }}

      terragrunt_modules_changed: ${{ steps.extract.outputs.terragrunt_modules_changed }}
      terragrunt_modules: ${{ steps.extract.outputs.terragrunt_modules }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Paths Filter
        id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d #vv4.0.1
        with:
          list-files: shell
          filters: |
            terraform-modules:
              - 'infra/modules/**'
            terragrunt-modules:
              - 'terragrunt/us-east-1/**'
            workflow:
              - '.github/workflows/validate-Infra-manifest.yaml'

      - name: Extract service list from changed files
        id: extract
        run: |
            set -euo pipefail

             #TERRAFORM MODULES

            TF_MODULES_FILES="${{ steps.filter.outputs.terraform-modules_files }}"
            if [ -n "$TF_MODULES_FILES" ]; then
              TF_MODULES=$(echo "$TF_MODULES_FILES" \
                | tr ' ' '\n' \
                | cut -d'/' -f3 \
                | sort -u \
                | jq -R -s -c 'split("\n") | map(select(length>0))')

              echo "terraform_modules_changed=true" >> $GITHUB_OUTPUT
              echo "terraform_modules=$TF_MODULES" >> $GITHUB_OUTPUT
            else
              echo "terraform_modules_changed=false" >> $GITHUB_OUTPUT
              echo "terraform_modules=[]" >> $GITHUB_OUTPUT
            fi
            
            # TERRAGRUNT MODULES
           
            TG_FILES="${{ steps.filter.outputs.terragrunt-modules_files }}"

            if [ -n "$TG_FILES" ]; then
              TG=$(echo "$TG_FILES" \
                | tr ' ' '\n' \
                | cut -d'/' -f4 \
                | sort -u \
                | jq -R -s -c 'split("\n") | map(select(length>0))')

              echo "terragrunt_modules_changed=true" >> $GITHUB_OUTPUT
              echo "terragrunt_modules=$TG" >> $GITHUB_OUTPUT
            else
              echo "terragrunt_modules_changed=false" >> $GITHUB_OUTPUT
              echo "terragrunt_modules=[]" >> $GITHUB_OUTPUT
            fi

            WORKFLOW="${{ steps.filter.outputs.workflow }}"

            if [ "$WORKFLOW" = "true" ]; then
              echo "workflow_changed=true" >> $GITHUB_OUTPUT
            else
              echo "workflow_changed=false" >> $GITHUB_OUTPUT
            fi

  terraform-scan:
    name: " Terraform Security Scan"
    runs-on: ubuntu-latest
    needs: detect-changes
    if: |
     needs.detect-changes.outputs.terraform_modules_changed == 'true'  ||  needs.detect-changes.outputs.workflow_changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        modules : ${{ fromJson(needs.detect-changes.outputs.terraform_modules) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Check Terraform manifest logic
        if: needs.detect-changes.outputs.terraform_modules_changed == 'true'
        working-directory: infra/modules/${{ matrix.modules }}
        run: |
          terraform init -backend=false
          terraform validate


      - name: Run Checkov on Terraform
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infra/modules/${{ matrix.modules }}
          framework: terraform
          soft_fail: false
          skip_check: CKV_AWS_39,CKV_AWS_58  # Public EKS endpoint (intentional for dev)
          output_format: cli

  terragrunt-scan:
    name: " Terragrunt logic Scan"
    runs-on: ubuntu-latest
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.terragrunt_modules_changed == 'true' ||  needs.detect-changes.outputs.workflow_changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        modules : ${{ fromJson(needs.detect-changes.outputs.terragrunt_modules) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terragrunt and OpenTofu
        uses: gruntwork-io/terragrunt-action@v3
        with:
              tg_version: '0.82.2'
              tofu_version: '1.10.1'

      - name: Check Terragrunt manifest logic in dev
        if: inputs.env == 'dev'
        working-directory: terragrunt/us-east-1/${{inputs.env}}
        run: |
          terragrunt run-all validate

      - name: Check Terragrunt manifest logic in prod
        if: inputs.env == 'prod'
        working-directory: terragrunt/us-east-1/${{inputs.env}}
        run: |
          terragrunt run-all validate

  call-terraform-for-dev:
        if: |
         github.ref == 'refs/heads/dev' && 
         github.event_name == 'push' &&  
         (
         needs.detect-changes.outputs.terragrunt_modules_changed == 'true' ||
         needs.detect-changes.outputs.terraform_modules_changed == 'true' ||  
         needs.detect-changes.outputs.workflow_changed == 'true'
         )
        needs:
          - terragrunt-scan
          - terraform-scan
          - detect-changes
        uses: ./.github/workflows/workflow-call.yaml
        with: 
            env : ${{ inputs.env || 'dev' }}
            action: ${{ inputs.action }}
            aws_region: ${{ vars.AWS_REGION }}
        secrets: inherit
        
  call-terraform-for-prod:
        if: |
         github.ref == 'refs/heads/main'&& 
         github.event_name == 'push' &&  
         (
         needs.detect-changes.outputs.terragrunt_modules_changed == 'true' ||
         needs.detect-changes.outputs.terraform_modules_changed == 'true'|| 
         needs.detect-changes.outputs.workflow_changed == 'true'
         )
        needs:
          - terragrunt-scan
          - terraform-scan
          - detect-changes
        uses: ./.github/workflows/workflow-call.yaml
        with: 
            env : ${{ inputs.env || 'prod' }} 
            action: ${{ inputs.action }}
            aws_region: ${{ vars.AWS_REGION }}
        secrets: inherit